version: "3.1"

services:
  db:
    image: postgres
    restart: always
    container_name: chainlink_postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: chainlink
    ports:
      - 8081:8081
      - 5432:5432

  adminer:
    image: adminer
    container_name: postgres_adminer
    restart: always
    ports:
      - 8080:8080
